// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zihevlplqeadyjkrkbdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaGV2bHBscWVhZHlqa3JrYmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzI1NjAsImV4cCI6MjA3MDA0ODU2MH0.kGyUwaO-TuTYufpGC-_ekuKfNOtZZHk5GqZdPoEnG2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);